### ISSUE TITLE
JavaScript import statement nor require statement is working and DOM query returns null/undefined always

### ISSUE THREAD

**Issue by Anish-Karthik** [Anish-Karthik/youTube-clone#1]
JavaScript import statement nor require statement is working and DOM query returns null/undefined always

branch: javaScript
file: index.js

even after using export in data.js and import in index.js is still not working 
"even though I have given syntax and file location correctly"

all elements using querySelector return undefined when accessing inner HTML. 
if I managed to get it using getElementsByClassName also changes are not reflected.

also, the append child is not working

jquery is also not working

**Comment by anmol111pal** [comment]
When using getElementsByClassname() -> it returns an array of all the a=matching elements with the specified classname.

Use getElementsByClassname("...")[0]
